version: '3.8'

services:
  api:
    build: .
    container_name: fig-api
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PGPASSWORD=sejal2001